[book]
authors = ["Andie Similon, Sam Van Battel, Jeroen De Vos, David Verhulst"]
language = "be-nl"
multilingual = false
src = "."
title = "Web Programming"
[output.html.fold]
enable = true

[output.html]
no-section-label = true
additional-css = ["./custom.css"]